### PR TITLE
fix: usage of uft8 code for apostrophe

### PR DESCRIPTION
**Pull request by DuMaM**
In #160 I changed apostrophe to unicode value to improve IDE highlighting.
I did small typo in this change which i missed.
This PR will fix it.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

<a href="https://gitpod.io/#https://github.com/jenkinsci/design-library-plugin/pull/162"></a>

### CODE REVIEW

**Review by timja — COMMENTED** [review]
these files should already be encoded as utf-8 why escape them?

**Review by basil — CHANGES_REQUESTED** [review]
Per [the Javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/MessageFormat.html):

> A single quote itself must be represented by doubled single quotes `''` throughout a _String_.

**Comment by DuMaM** [comment]
> Per [the Javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/MessageFormat.html):
> 
> > A single quote itself must be represented by doubled single quotes `''` throughout a _String_.

This is even better option :) Ok I will apply this

**Comment by DuMaM** [comment]
@basil 
```
The rules for using quotes within message format patterns unfortunately have shown to be somewhat confusing. In particular, it isn't always obvious to localizers whether single quotes need to be doubled or not. Make sure to inform localizers about the rules, and tell them (for example, by using comments in resource bundle source files) which strings will be processed by MessageFormat. Note that localizers may need to use single quotes in translated strings where the original version doesn't have them.
```

**Comment by basil** [comment]
:thumbsup:

**Comment by DuMaM** [comment]
> 👍

Should i still change it to `' '`?

**Comment by basil** [comment]
I do not see a reason not to.

**Review by basil — APPROVED** [review]
I pushed another commit to fix more apostrophes that were incorrectly encoded in English properties files. I have not made an effort to fix incorrectly encoded apostrophes in non-English properties files, nor have I made an effort to fix other quoting errors relating to single quotes in English properties files.

**Pull request merged**
