### PR TITLE
Improve dark/normal mode banner detection

### PR DESCRIPTION
**Pull request by NotMyFault**
Additionally, we do now link to weekly.ci.

<a href="https://gitpod.io/#https://github.com/jenkinsci/design-library-plugin/pull/69"></a>

### CODE REVIEW

**Review by timja — COMMENTED** [review]
Doesn't seem to work:

image

**Comment by NotMyFault** [comment]
Might not be out for every user yet, but was included in today's changelog: https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/

**Comment by timja** [comment]
Oo cool, there was also an alternative here as well:
https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/84

**Comment by NotMyFault** [comment]
> Looks good to me!
> 
> Off topic but I do wish GitPod would use a high res button 😶
> 
> image

Might be down to mobile, the browser version uses a SVG here.

**Review by timja — APPROVED** [review]
doesn't work for me but meh i'm sure it should work soon, 

i assume it works for you?

**Comment by NotMyFault** [comment]
> doesn't work for me but meh i'm sure it should work soon,
> 
> i assume it works for you?

I'd rather keep it on hold a little longer, considering this feature is in beta still and not available to everyone yet, which may get a rid of the banner at all for some people.

**Comment by timja** [comment]
yeah still doesn't show up for me

**Comment by NotMyFault** [comment]
> yeah still doesn't show up for me

I guess that is good to go now, considering you approved my core PR? 👀

**Review by timja — APPROVED** [review]

**Pull request merged**
