### PR TITLE
Updated gitpod to use Java 21

### PR DESCRIPTION
**Pull request by shinigami-777**
Fixes [#367](https://github.com/jenkinsci/design-library-plugin/issues/367). This pr automates the process of installing and using Java 21 for Gitpod.

### Testing done
I have tested the changes with Gitpod.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by krisstern** [comment]
Duplicated, see #373

**Comment by shinigami-777** [comment]
@krisstern I have tested #373 before and there are formatting mistakes so gitpod workspace is not working. Also this pr had a different approach .

**Comment by krisstern** [comment]
We do not accept two PR's for the same issue. Also, the other PR was created before this one. Maybe next time you should check if there is already an active PR for an issue you are interested in before submitting.

**Comment by shinigami-777** [comment]
Sorry for the confusion. I'd be careful not to do so. I only meant to share a different approach for the solution.
Should I open a different issue for having the `.gitpod.Dockerfile`?

**Comment by krisstern** [comment]
I am sorry but why do we need a separate and non-standard `.gitpod.Dockerfile`? Could you provide more context?

**Comment by shinigami-777** [comment]
Since the Gitpod Workspace by default uses Java 11. So we can use a non-standard image that has Java 21

**Comment by krisstern** [comment]
I don't think that is needed if #373 is sufficient. But thanks for the suggestion! If you are interested in contributing maybe it is better to pick another issue to work on.

**Comment by timja** [comment]
> We do not accept two PR's for the same issue. Also, the other PR was created before this one. Maybe next time you should check if there is already an active PR for an issue you are interested in before submitting.

2 pull requests for the same issue are fine if they are different, we'll select one at merge time and close the other thanking both contributors.

The dockerfile may be slightly better as you can get caching whereas for this I think you can't.
But sdkman should be used for installing it so-as we are more flexible on the version and distribution,

An example of how Jenkins core works:
https://github.com/jenkinsci/jenkins/blob/master/.gitpod/Dockerfile

**Comment by krisstern** [comment]
@timja I checked their approaches were similar to begin with, both without the use of Dockerfile at first. Also, the other contributor indicated he was working on this issue and had submitted a patch for this. As much as I like to have two competing approaches this was not one of those cases.

**Pull request closed without merging**
